"use client"
import { useState } from "react"

type Replay = "baseline" | "drift" | "blocked"
type Worker = { name: string; progress: number; throughput: string; wait: string; risk: string; state: string }
type Reading = { label: string; action: string; detail: string; progress: number; eta: string; inputWait: string; cost: string; throughput: string; step: string; workers: Worker[] }
const data: Record<Replay, Reading> = {
  baseline:{label:"Running",action:"Keep observing",detail:"All workers are progressing within the expected range.",progress:72,eta:"43 min",inputWait:"12 ms",cost:"€0",throughput:"1.82k/s",step:"M0 65H14V48H25V61H38V34H49V58H62V46H74V64H86V38H100",workers:[{name:"worker-01",progress:72,throughput:".46k/s",wait:"12 ms",risk:"€0",state:"healthy"},{name:"worker-02",progress:71,throughput:".45k/s",wait:"14 ms",risk:"€0",state:"healthy"},{name:"worker-03",progress:73,throughput:".47k/s",wait:"11 ms",risk:"€0",state:"healthy"},{name:"worker-04",progress:70,throughput:".44k/s",wait:"15 ms",risk:"€0",state:"healthy"}]},
  drift:{label:"Review needed",action:"Review worker-04",detail:"One worker is falling behind. Investigate before restarting.",progress:70,eta:"58 min",inputWait:"86 ms",cost:"€14",throughput:"1.46k/s",step:"M0 66H14V48H25V61H38V34H49V58H62V46H74V76H86V42H100",workers:[{name:"worker-01",progress:76,throughput:".49k/s",wait:"14 ms",risk:"€0",state:"healthy"},{name:"worker-02",progress:74,throughput:".48k/s",wait:"16 ms",risk:"€0",state:"healthy"},{name:"worker-03",progress:75,throughput:".49k/s",wait:"15 ms",risk:"€0",state:"healthy"},{name:"worker-04",progress:54,throughput:".18k/s",wait:"86 ms",risk:"€14",state:"lagging"}]},
  blocked:{label:"Intervention needed",action:"Prepare worker restart",detail:"The delay is material. Restarting is the lowest-cost reversible action.",progress:66,eta:"1h 18m",inputWait:"231 ms",cost:"€39",throughput:"0.94k/s",step:"M0 66H14V48H25V61H38V34H49V58H62V80H74V91H86V72H100",workers:[{name:"worker-01",progress:80,throughput:".49k/s",wait:"16 ms",risk:"€0",state:"healthy"},{name:"worker-02",progress:78,throughput:".48k/s",wait:"18 ms",risk:"€0",state:"healthy"},{name:"worker-03",progress:79,throughput:".49k/s",wait:"17 ms",risk:"€0",state:"healthy"},{name:"worker-04",progress:29,throughput:".06k/s",wait:"231 ms",risk:"€39",state:"blocked"}]},
}
function ParticleField({workers}:{workers:Worker[]}){return <svg className="particle-field" viewBox="0 0 440 270" aria-label="Workload topology">{Array.from({length:150},(_,i)=>{const a=i*2.399;const r=18+(i%48)*2.5;return <circle key={i} cx={160+Math.cos(a)*r} cy={140+Math.sin(a)*r*.72} r={i%11===0?2.2:1} className="particle" />})}{workers.map((w,i)=>{const a=[-.7,-.15,.45,1.05][i];const x=160+Math.cos(a)*118;const y=140+Math.sin(a)*82;return <g key={w.name} className={`field-node ${w.state}`}><path d={`M160 140 Q${(160+x)/2} ${i%2?55:220} ${x} ${y}`} /><circle cx={x} cy={y} r="9" /><text x={x} y={y+27}>{`w-${i+1}`}</text></g>})}</svg>}
function Ring({value,state}:{value:number;state:string}){return <span className={`health-ring ${state}`} style={{"--ring":`${value*3.6}deg`} as React.CSSProperties}><b>{value}%</b></span>}
export function GpuJobTriageDemo(){const [replay,setReplay]=useState<Replay>("drift");const d=data[replay];return <section className="gpu-triage" id="gpu-job-triage"><header className="gpu-triage-intro"><div><span>Local product prototype</span><h2>Make the next action visible.</h2></div><p>A decision surface for a distributed AI job, grounded in Grafana and Prometheus locally.</p></header><div className="triage-product triage-v2"><header><strong>vision-batch-07</strong><div>{(Object.keys(data) as Replay[]).map(k=><button key={k} onClick={()=>setReplay(k)} className={replay===k?"is-active":""}>{k}</button>)}</div></header><div className="triage-main-v2"><article className="triage-hero-v2"><span>{d.label}</span><ParticleField workers={d.workers}/><div className="hero-readings"><h3>Distributed AI job</h3><div><i className="metric-bar"/><b>{d.progress}%</b><small>job progress</small></div><div><i className="metric-bar is-wait"/><b>{d.inputWait}</b><small>input wait</small></div><p>{d.detail}</p><i>▁▃▂▅▂▇▅▃▆ LIVE</i></div></article><aside className="triage-usage"><h3>Input wait</h3><svg viewBox="0 0 100 100"><path d="M0 20H100M0 50H100M0 80H100"/><path d={d.step}/><circle cx="74" cy={replay==="blocked"?91:replay==="drift"?76:46} r="3"/></svg><div><span><b>Throughput</b>{d.throughput}</span><span><b>Queue</b>{replay==="blocked"?"32":replay==="drift"?"10":"3"}</span><span><b>Retries</b>{replay==="blocked"?"8%":replay==="drift"?"2%":"0%"}</span></div><section><span>Recommended action</span><strong>{d.action}</strong><small>ETA {d.eta} · Cost at risk {d.cost}</small></section></aside></div><section className="worker-health"><header><span>Worker health</span><span>Progress</span><span>Throughput</span><span>Input wait</span><span>Cost at risk</span></header>{d.workers.map(w=><div key={w.name}><strong>{w.name}</strong><Ring value={w.progress} state={w.state}/><span>{w.throughput}</span><span>{w.wait}</span><span>{w.risk}</span></div>)}</section><footer>Built with Grafana + Prometheus locally. Portfolio replay uses simulated workload data.</footer></div></section>}
