"use client"

import { useState } from "react"

type Replay = "baseline" | "drift" | "blocked"
type JobState = { label: string; verdict: string; action: string; detail: string; eta: string; cost: string; workers: { name: string; value: number; state: string }[] }

const states: Record<Replay, JobState> = {
  baseline: { label: "On track", verdict: "No intervention needed.", action: "Keep observing", detail: "All workers are progressing within the expected range.", eta: "43 min", cost: "€0", workers: [{ name: "worker-01", value: 72, state: "healthy" }, { name: "worker-02", value: 71, state: "healthy" }, { name: "worker-03", value: 73, state: "healthy" }, { name: "worker-04", value: 70, state: "healthy" }] },
  drift: { label: "Progress diverging", verdict: "Inspect worker-04.", action: "Review worker logs", detail: "One worker is falling behind. The gap is widening but a restart can still wait.", eta: "58 min", cost: "€14", workers: [{ name: "worker-01", value: 76, state: "healthy" }, { name: "worker-02", value: 74, state: "healthy" }, { name: "worker-03", value: 75, state: "healthy" }, { name: "worker-04", value: 54, state: "lagging" }] },
  blocked: { label: "Worker blocked", verdict: "Restart worker-04.", action: "Prepare worker restart", detail: "The delay is material. Restarting is the lowest-cost reversible action.", eta: "1h 18m", cost: "€39", workers: [{ name: "worker-01", value: 80, state: "healthy" }, { name: "worker-02", value: 78, state: "healthy" }, { name: "worker-03", value: 79, state: "healthy" }, { name: "worker-04", value: 29, state: "blocked" }] },
}

function Topology({ workers }: { workers: JobState["workers"] }) {
  const points = [[92,68],[203,38],[225,148],[108,180]]
  return <svg className="triage-topology" viewBox="0 0 300 230" role="img" aria-label="Distributed workload topology"><defs><radialGradient id="topologyGlow"><stop stopColor="#45e4e0" stopOpacity=".36" /><stop offset="1" stopColor="#45e4e0" stopOpacity="0" /></radialGradient></defs><circle cx="150" cy="114" r="107" fill="url(#topologyGlow)" />{points.map(([x,y], i) => points.slice(i + 1).map(([tx,ty], j) => <path key={`${i}-${j}`} d={`M${x} ${y} Q150 ${114 + (i % 2 ? -18 : 18)} ${tx} ${ty}`} className="triage-link" />))}<circle cx="150" cy="114" r="25" className="triage-core" /><text x="150" y="118" textAnchor="middle">JOB</text>{workers.map((worker, i) => { const [x,y] = points[i]; return <g key={worker.name} className={`triage-node is-${worker.state}`}><circle cx={x} cy={y} r="20" /><circle cx={x} cy={y} r="8" /><text x={x} y={y + 38} textAnchor="middle">{worker.name.replace("worker-", "w-")}</text></g>})}</svg>
}

export function GpuJobTriageDemo() {
  const [replay, setReplay] = useState<Replay>("drift")
  const state = states[replay]
  const progress = Math.round(state.workers.reduce((total, worker) => total + worker.value, 0) / 4)
  return <section className="gpu-triage" id="gpu-job-triage" aria-labelledby="gpu-job-triage-title"><header className="gpu-triage-intro"><div><span>Local product prototype</span><h2 id="gpu-job-triage-title">Make the next action visible.</h2></div><p>A decision surface for a distributed AI job, grounded in a local Grafana and Prometheus stack.</p></header><div className="triage-product"><header><div><span>Training run</span><strong>vision-batch-07</strong></div><div className="triage-replay" role="group" aria-label="Replay an incident">{(Object.keys(states) as Replay[]).map(key => <button type="button" onClick={() => setReplay(key)} className={replay === key ? "is-active" : ""} key={key}>{key}</button>)}</div></header><div className="triage-product-grid"><section className="triage-hero-card"><span className={`triage-state is-${replay}`}>{state.label}</span><Topology workers={state.workers} /><div className="triage-summary"><p>Distributed workload</p><strong>{progress}%</strong><span>job progress</span><div><b>{state.eta}</b><small>expected completion</small></div></div><footer><span>Local workload replay</span><span>Prometheus signals</span></footer></section><aside className="triage-side"><section><span>Recommended action</span><h3>{state.verdict}</h3><p>{state.detail}</p><button type="button">{state.action} <b>↗</b></button></section><section className="triage-reading"><div><span>Cost at risk</span><strong>{state.cost}</strong></div><div><span>Workers healthy</span><strong>{state.workers.filter(worker => worker.state === "healthy").length} / 4</strong></div></section><section className="triage-trace"><span>Decision trace</span><ol><li>Worker-04 progress dropped below group range</li><li>ETA variance passed the review threshold</li><li>Container pressure increased after the delay</li></ol></section></aside></div><footer className="triage-product-footer">Built with Grafana + Prometheus locally. This portfolio replay uses the same scenario with simulated workload data.</footer></div></section>
}
